# Generated by Django 3.2 on 2021-05-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_auto_20210529_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='phone_number',
        ),
    ]
